Banners/Areas/Admin/Controllers/BannerStatsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banners.DAL.Context;
using Banners.DAL.Entities;
using Banners.Models.ViewModels;
using Banners.Service.Services.Implementations;
using Banners.Service.Services.Interfaces;
using Banners.Infrastructure.Structures;
using Microsoft.AspNetCore.Authorization;

namespace Banners.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class BannerStatsController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IBannerStatService _bannerStatService;

        public BannerStatsController(IWebHostEnvironment env, IBannerStatService bannerStatService)
        {
            _env = env;
            _bannerStatService = bannerStatService;
        }


        // GET: Admin/BannerStats
        public async Task<IActionResult> Index([FromQuery]Pagination pagination)
        {
            var banners = await _bannerStatService.GetPaginatedAsync(pagination);
            return View(banners);
        }
    }
}

Banners/Areas/Admin/Controllers/BannersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Banners.DAL.Context;
using Banners.DAL.Entities;
using Banners.Models.ViewModels;
using Banners.Service.Services.Implementations;
using Banners.Service.Services.Interfaces;
using Banners.Infrastructure.Structures;
using Microsoft.AspNetCore.Authorization;
using PagedList;

namespace Banners.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class BannersController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IBannerService _bannerService;

        public BannersController(IWebHostEnvironment env, IBannerService bannerService)
        {
            _env = env;
            _bannerService = bannerService;
        }


        // GET: Admin/Banners
        public async Task<IActionResult> Index([FromQuery]Pagination pagination)
        {
            var banners = await _bannerService.GetPaginatedAsync(pagination);

            return View(banners);
        }

        // GET: Admin/Banners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banner = new Banner();
            if (banner == null)
            {
                return NotFound();
            }

            return View(banner);
        }

        // GET: Admin/Banners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Banners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Image,LinkURL,Online,Order,FormFile")] InsertBannerViewModel bannerViewModel)
        {
            if (ModelState.IsValid)
            {
                await _bannerService.CreateAsync(bannerViewModel, _env.WebRootPath);
                return RedirectToAction(nameof(Index));
            }
            return View(bannerViewModel);
        }

        // GET: Admin/Banners/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var banner = await _bannerService.EditAsync(id);
            if (banner == null)
            {
                return NotFound();
            }
            return View(banner);
        }

        // POST: Admin/Banners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, 
            [Bind("Id,Title,ImageURL,LinkURL,Online,Order,AutoRotate,FormFile")] UpdateBannerViewModel bannerViewModel)
        {
            if (id != bannerViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _bannerService.UpdateAsync(bannerViewModel, _env.WebRootPath);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BannerExists(bannerViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bannerViewModel);
        }

        // GET: Admin/Banners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var banner = await _bannerService.FindAsync((int)id);

            if (banner == null)
            {
                return NotFound();
            }

            return View(banner);
        }

        // POST: Admin/Banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _bannerService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool BannerExists(int id)
        {
            return true;
            //return _context.Banner.Any(e => e.Id == id);
        }
    }
}

Banners/Areas/Admin/Views/Shared/_Aside.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-transition os-host-scrollbar-horizontal-hidden">
        <div class="os-resize-observer-host observed"><div class="os-resize-observer" style="left: 0px; right: auto;"></div></div><div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;"><div class="os-resize-observer"></div></div><div class="os-content-glue" style="margin: 0px -8px; width: 249px; height: 239px;"></div><div class="os-padding">
            <div class="os-viewport os-viewport-native-scrollbars-invisible" style="overflow-y: scroll;">
                <div class="os-content" style="padding: 0px 8px; height: 100%; width: 100%;">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="~/admin/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">Alexander Pierce</a>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Banners" asp-action="Index">
                                    <i class="nav-icon far fa-circle text-danger"></i>
                                    <p class="text">Banners</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="BannerStats" asp-action="Index">
                                    <i class="nav-icon far fa-circle text-danger"></i>
                                    <p class="text">Banner Stats</p>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
        </div>
        <div class="os-scrollbar-corner">
        </div>
    </div>
    <!-- /.sidebar -->
</aside>

Banners/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Banners</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Tabbed IFrames</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/admin/plugins/fontawesome-free/css/all.min.css">

    <link rel="stylesheet" href="~/admin/dist/css/adminlte.css" asp-append-version="true" />
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

    <link rel="stylesheet" href="~/Banners.styles.css" asp-append-version="true" />
</head>
<body class="sidebar-mini layout-fixed dark-mode" data-panel-auto-height-mode="height" style="height: auto;">

    @{
        await Html.RenderPartialAsync("_Aside");
    }

    <div class="content-wrapper" data-auto-dark-mode="true" data-loading-screen="750" style="height: 100%;">
        <div class="tab-content container">
            <div class="tab-empty" style="height: 634px; display: none;">
                <h2 class="display-4">No tab selected!</h2>
            </div>
            <div class="tab-loading" style="height: 634px; display: none;">
                <div>
                    <h2 class="display-4">Tab is loading <i class="fa fa-sync fa-spin"></i></h2>
                </div>
            </div>
            <div class="tab-pane fade" id="panel-pages-mailbox-mailbox-html" role="tabpanel" aria-labelledby="tab-pages-mailbox-mailbox-html">
            </div>

            <div class="tab-pane fade active show"
                 id="panel-pages-search-simple-html" role="tabpanel" aria-labelledby="tab-pages-search-simple-html">
                @RenderBody()

            </div>
        </div>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>